variables:
  MYSQL_DATABASE: hust_elearning_english
  MYSQL_ROOT_PASSWORD: password
  BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - build
  - test
  - deploy

maven-build:
  image:  maven:3.6.1-jdk-11-slim
  stage: build
  tags:
    - ryan-ec2-ubuntu
  script:
    - echo "Building app..."
    - mvn clean install
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - target/*.jar
  only:
    - master

deploy:
  stage: deploy
  image: alpine:3.11
  tags:
    - ryan-ec2-ubuntu
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying started..."
    - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop consoleapp.service"
    - scp ./target/*.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
    - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
    - echo "Finished deploying the app."
  only:
    - master
