version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=hust_elearning_english
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    networks:
      springboot-mysql-net:

  app:
    container_name: toeicapp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: "no"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3307/hust_elearning_english?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    ports:
      - "8080:8080"
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: