version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=hust_elearning_english
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-net:

  app:
    container_name: toeicapp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: