cloud:
  aws:
    credentials:
#      access-key: AKIA4K6HKSE6IA3TJ6OO
#      secret-key: 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
      access-key: AKIAWMTNGN6Z3NLHR2XV
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: toeicapps3


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 20MB
      max-request-size: 25MB
